services:
    lmdi.delre.listener:
        class: lmdi\delre\event\listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
